// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: fokus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FokusServiceClient is the client API for FokusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FokusServiceClient interface {
	GetFokus(ctx context.Context, in *GetFokusRequest, opts ...grpc.CallOption) (*GetFokusResponse, error)
}

type fokusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFokusServiceClient(cc grpc.ClientConnInterface) FokusServiceClient {
	return &fokusServiceClient{cc}
}

func (c *fokusServiceClient) GetFokus(ctx context.Context, in *GetFokusRequest, opts ...grpc.CallOption) (*GetFokusResponse, error) {
	out := new(GetFokusResponse)
	err := c.cc.Invoke(ctx, "/fokus.FokusService/GetFokus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FokusServiceServer is the server API for FokusService service.
// All implementations should embed UnimplementedFokusServiceServer
// for forward compatibility
type FokusServiceServer interface {
	GetFokus(context.Context, *GetFokusRequest) (*GetFokusResponse, error)
}

// UnimplementedFokusServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFokusServiceServer struct {
}

func (UnimplementedFokusServiceServer) GetFokus(context.Context, *GetFokusRequest) (*GetFokusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFokus not implemented")
}

// UnsafeFokusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FokusServiceServer will
// result in compilation errors.
type UnsafeFokusServiceServer interface {
	mustEmbedUnimplementedFokusServiceServer()
}

func RegisterFokusServiceServer(s grpc.ServiceRegistrar, srv FokusServiceServer) {
	s.RegisterService(&FokusService_ServiceDesc, srv)
}

func _FokusService_GetFokus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFokusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FokusServiceServer).GetFokus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fokus.FokusService/GetFokus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FokusServiceServer).GetFokus(ctx, req.(*GetFokusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FokusService_ServiceDesc is the grpc.ServiceDesc for FokusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FokusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fokus.FokusService",
	HandlerType: (*FokusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFokus",
			Handler:    _FokusService_GetFokus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fokus.proto",
}
